### ISSUE TITLE
Replacing vanilla trades broken in v1.0.7.

### ISSUE THREAD

**Issue by crux-f** [GC-spigot/AdvancedTrades#7]
### Describe the bug

After configuring custom trades for this plugin, it began throwing an error whenever a villager is interacted with:
**Could not pass event VillagerAcquireTradeEvent to AdvancedTrades v1.0.7**
The plugin loads successfully, including the trades.yml (included as a .txt here) [trades.txt](https://github.com/GC-spigot/AdvancedTrades/files/7798422/trades.txt).

Disabling any requiredBiome and requiredProfession fields included in the trades.yml fixes the issue, but renders both of those features completely unusable.
**Things I have tried so far:**
- Enabling and disabling the 'disableVanillaTrades' option in the config.yml file for AdvancedTrades
- Uninstalling all other plugins I use
- Starting with both Spigot (latest) and Paper build #103 (also latest)

I have so far been unable to make the custom trading feature work in any capacity. This may be partially related to one of the previous issues posted about the requiredProfession field.

I was asked to post this latest.txt log file to this GitHub on a support ticket; I hope I will be able to start using the plugin soon.
[latest.log](https://github.com/GC-spigot/AdvancedTrades/files/7798426/latest.log)

### How to reproduce

Start Spigot or Paper server with a custom trade loaded. If the trade uses the requiredProfession or requiredBiome field, you receive this error any time a villager is right-clicked:

Could not pass event VillagerAcquireTradeEvent to AdvancedTrades v1.0.7

[08:50:53] [Server thread/ERROR]: Could not pass event VillagerAcquireTradeEvent to AdvancedTrades v1.0.7
java.lang.IllegalStateException: null
	at java.util.ArrayList$Itr.remove(ArrayList.java:980) ~[?:?]
	at net.advancedplugins.at.handlers.TradeBuilder.build(TradeBuilder.java:72) ~[AdvancedTrades-1.0.7.jar:?]
	at net.advancedplugins.at.listeners.VillagerTradesPopulator.onVillagerAcquireTradeEvent(VillagerTradesPopulator.java:37) ~[AdvancedTrades-1.0.7.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-103]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.npc.AbstractVillager.addOffersFromItemListings(AbstractVillager.java:288) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.updateTrades(Villager.java:951) ~[?:?]
	at net.minecraft.world.entity.npc.AbstractVillager.getOffers(AbstractVillager.java:129) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.needsToRestock(Villager.java:399) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.shouldRestock(Villager.java:437) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.WorkAtPoi.start(WorkAtPoi.java:58) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.WorkAtPoi.canStillUse(WorkAtPoi.java:18) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.Behavior.tryStart(Behavior.java:61) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.world.entity.ai.behavior.GateBehavior$RunningPolicy$1.apply(GateBehavior.java:120) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.GateBehavior.start(GateBehavior.java:56) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.Behavior.tryStart(Behavior.java:61) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.world.entity.ai.Brain.startEachNonRunningBehavior(Brain.java:511) ~[?:?]
	at net.minecraft.world.entity.ai.Brain.tick(Brain.java:470) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.mobTick(Villager.java:248) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:245) ~[?:?]
	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:865) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3251) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:628) ~[?:?]
	at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2907) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:396) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.tick(Villager.java:290) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-103]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-103]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Screenshots / Videos

![Could_Not_Pass_Event_Error](https://user-images.githubusercontent.com/5208142/147863673-a78b0b83-487c-40b1-93b3-b0bb582e27cd.PNG)

### Server Log

https://mcpaste.io/436d5b703444c96c

**Comment by crux-f** [comment]
Good morning,

I understand that plugin development is a difficult and often thankless endeavor, but I have under a month left to get my server prepared for 1.18.1, and this plugin requires a significant amount of configuration and testing before the server launches.

I have gone through the proper channels and provided as much information as I possibly can, and in ten days, I have received no suggestions as to what I should do to make this plugin functional.

Given that this is the only Minecraft plugin I have ever paid money for, I was hoping that I could get it working with relative ease, and so far nothing I have tried has worked, and the only communication I have had from the developers is requests for me to jump through more hoops.

I know that communication has been more difficult considering the holidays, differing time zones, and I'm sure more going on behind the scenes that I don't know about, and I would greatly appreciate it if someone could let me know if I will be able to make any use of this plugin going forward, or if I should search for an alternative.

Let me know,

Thank you

**Comment by GC-spigot** [comment]
Sorry about delays! My mom is very sick, it's the holidays season and I have exams - everything hit me/family at once. I'm looking at this now and will let you know what I find.

**Comment by GC-spigot** [comment]
Fixed!

**Comment by crux-f** [comment]
@GC-spigot I appreciate the reply, thank you very much for taking the time to look over the issue.
I am sorry to hear about your mom and wish you and her the best.

**Comment by crux-f** [comment]
@GC-spigot 
Hi there,
After doing some testing with the 1.08 release, I unfortunately have to report that the issue is still present, although it has changed slightly.

This error occurs in 1.08 whenever I interact with a villager as before, but ONLY if there are trades in the trades.yml that are assigned to different professions. For example, if I remove all trades except the ones for Armorer, it works as intended, however if I add even one trade for Butcher, the error returns.

Should I submit a new issue or should this one be re-opened?
